app:
  name: MyDummyAppOne
  version: 1.0.0
  debug: true


database:
  engine: postgres
  host: localhost
  port: 5432
  username: user
  password: pass
  name: myapp_db

logging:
  level: INFO
  file: logs/dummyappone.log
